name: Test and Deploy to AWS Lambda

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy the correct config file based on branch
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
          cp config_production.json config.json
        elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
          cp config_develop.json config.json
        else
          cp config_develop.json config.json
        fi

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        pytest tests/

  deploy:
    needs: test  # This makes deploy wait for test to succeed
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy the correct config file based on branch
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
          cp config_production.json config.json
        elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
          cp config_develop.json config.json
        else
          cp config_develop.json config.json
        fi

    - name: Set environment variables
      id: env_vars
      run: ./set_env_vars.sh

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install only production dependencies in the package directory
        if [ -f requirements.txt ]; then
          # Create a temporary requirements file without test dependencies
          grep -v "moto\|pytest" requirements.txt > requirements.prod.txt
          pip install -r requirements.prod.txt -t ./package
        fi

    - name: Package code
      run: |
        # Only copy the necessary files, excluding tests and dev files
        mkdir -p ./package
        rsync -r \
          --exclude=package \
          --exclude=tests \
          --exclude=*.pyc \
          --exclude=__pycache__ \
          --exclude=requirements.txt \
          --exclude=requirements.prod.txt \
          --exclude=.pytest_cache \
          --exclude=.git \
          . ./package/
        cd package
        zip -r ../function.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with: 
        audience: sts.amazonaws.com
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-east-1

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code --function-name ${{ steps.env_vars.outputs.FUNCTION_NAME }} --zip-file fileb://function.zip | jq 'del(.Environment)' | cat
